### ISSUE TITLE
Mismatched queue names are used when pin values have more than one key-value pair

### ISSUE THREAD

**Issue by cicavey** [disintegrator/seneca-amqp-transport#11]
The example only uses a single pin, "role:create", which works fine. If you add more detail to the pin such as "role:create,type:random" communication will be impossible. The cause is that the queue names generated to match each pin are not generated correctly by the client resulting in the inability of rabbit to route messages.

I have attempted to fix this (pull request incoming) by extracting the queue name generation to a single common place and then calling in both listen and client code paths. I have also updated the the examples to include multiple value pins.

**Comment by nfantone** [comment]
@cicavey You are completely right. I'll dive into this.

**Comment by nfantone** [comment]
This has been fixed by #15. Already on `develop`. Will land on `0.2.0`.
