### ISSUE TITLE
Question about mq type transports

### ISSUE THREAD

**Issue by tuncaulubilge** [disintegrator/seneca-amqp-transport#14]
Hi,

I'm quite new to Seneca. So far, I'm loving it but got confused on message queue type transports.

Assume I got two services, an api service and a recommendation engine service, communicating via AMQ transport. In a traditional scenario, when a user makes a request to api service, api service sends the action to recommendation engine, recommendation engine finds the product and sends it back to the api service, api service receives the recommended product, and sends it back to the user.

This requires a bi-directional transport layer. How does seneca message queue plugins achieve this bi-directional communication? Does the recommendation service create a response message, which in turn received by the api service? 

In my previous projects, I used message/job queues uni-directional. The main server creates a job, sends it to the message queue and moves on without waiting for the job workers. On a separate machine, the workers fetches the job and completes, without informing the main server. Is it possible to achieve this with Seneca mq transports?

**Comment by nfantone** [comment]
@tuncaulubilge Yes, it's quite possible. Currently, the plugin works in an RPC fashion: there's an async response for every request and a client will keep listening for it until either it arrives or timeouts.

So, in your particular scenario, the API would `.act` and request recommendations for some user. Your recommendations microservice, should `.add` a listener and consume messages from the API (or any other service). When a request arrives, it may search for those recommended items and return them back to the API.

I recommend you start by following the [Getting Started](http://senecajs.org/get-started/) guide on Seneca.js. Once you get a grip on how things work, you can give [our examples](https://github.com/disintegrator/seneca-amqp-transport#run-the-examples) a try and see how the mechanism actually works.

**Comment by nfantone** [comment]
Closed due to inactivity.
