### ISSUE TITLE
Typo in the npm module uri parsing code

### ISSUE THREAD

**Issue by OriginalEXE** [disintegrator/seneca-amqp-transport#20]
Hello,

I noticed that the development branch fixes the issue with the url parsing (`join('://')` instead of `join('//')`), was wondering if you plan on merging it to master soon?

Thank you for the plugin!

**Comment by nfantone** [comment]
Hi, @OriginalEXE! I'm thinking of publishing the URI parser as a separate npm module. Will get into that right now.

Thanks for the feedback.

**Comment by nfantone** [comment]
Done. Already on `0.2.1`.
