### ISSUE TITLE
Question about scaling/loadbalancing

### ISSUE THREAD

**Issue by OriginalEXE** [disintegrator/seneca-amqp-transport#21]
Hello,

I was wondering what is the best way to scale the microservices system that is using amqp for the transport?

Say I have a high load on my application and I want to introduce more services of the same type and share load between them, as far as I understand this will be problematic because (at least by default) the queues are exclusive so I can't have two services listening on the same pin. Is the proper solution to spin another rabbitmq server?

I see in options there is an "exclusive" property for the response, is changing that to false the proper way to do it? If so, why is it exclusive by the default?

Thank you in advance!

**Comment by nfantone** [comment]
@OriginalEXE You absolutely can spawn more than one microservice. If you register them with the same set of pins, new consumers will be declared on RabbitMQ. The `exclusive` queues are only those tied to responses, which are randomly named and short lived.

**Comment by OriginalEXE** [comment]
Hmm it might be I messed something else up. Will test again tonight and let you know. Thanks again!

**Comment by nfantone** [comment]
Please, do and let me know if I can be of help.

**Comment by vigneshnrfs** [comment]
To extend @OriginalEXE question further, is it possible to have multiple microservices listening on the same pin but carry out different functions. Basically like a fan out method.

**Comment by nfantone** [comment]
@vigneshnrfs You can. But it won't be _exactly_ like a fanout exchange. And there are certain gotchas you'd have to be aware of. If you have multiple microservices registered with the same pin carrying on different tasks, you'll end up with multiple queues bound to the same routing key on a topic exchange (on default settings, at least). A fanout exchange doesn't care about the routing key, whereas in this topology you'd have to publish your messages with a certain pattern to make it work (which is automatically handled by the plugin).

On the other hand, if you do that you'd have _many responses_ (many listeners) for _one request_ (a client). And that is **not** supported by default in Seneca. It is doable, but you are going to have to do grunt work to succeed.

**Comment by vigneshnrfs** [comment]
@nfantone Thanks for the pointes. I think I will be able to work with you logic.

**Comment by nfantone** [comment]
@vigneshnrfs No worries.

I'll leave this issue open, waiting for input from @OriginalEXE.

**Comment by OriginalEXE** [comment]
Hello,

apologies for the delay, had no time last night.

Ok so it seems like I'm getting an error only when I have two identical .client() calls. The way I am testing this is I run my express server microservice using pm2 and I set "instances" to 2, so it spawns two of them in a cluster.

The exact error is:
```
Channel error on connection <0.765.0> (172.17.0.3:58414 -> 172.17.0.2:5672, vhost: '/', user: 'guest'), channel 1:
rabbitmq_1            | operation queue.declare caused a channel exception resource_locked: "cannot obtain exclusive access to locked queue 'seneca.res.pg:path:users,role:api,pin:role:api,path:users,type:amqp,url:amqp://rabbitmq-master' in vhost '/'"
```

Also, I am wondering, if I have multiple services listening for the same pin, which one will respond to the client? How is that determined, by speed of the response?

Thanks again, as you can see I am quite new to this concept so apologies for the noobish questions.

**Comment by nfantone** [comment]
@OriginalEXE No need to apologize. This is the right place to ask questions.

> Ok so it seems like I'm getting an error only when I have two identical .client() calls. 
As per your log prints, it _looks like_ you are manually setting the response queue name. Be careful with that. Response queues are randomly named to avoid name clashing. See the [warning in the README.md](https://github.com/disintegrator/seneca-amqp-transport/blob/develop/README.md#how-it-works).

If I'm right, just remove the `name` attribute on the client's options.

> Also, I am wondering, if I have multiple services listening for the same pin, which one will respond to the client? How is that determined, by speed of the response?
Read my [previous response](https://github.com/disintegrator/seneca-amqp-transport/issues/21#issuecomment-213418935) to @vigneshnrfs.

**Comment by OriginalEXE** [comment]
Thank you for the answer.

1.) I am not setting the name manually, I have read the warning in the README about it before using the plugin. Here is my whole seneca.js file for the express server:

```
'use strict';

let seneca = require( 'seneca' )();

seneca
	.use( 'seneca-amqp-transport' )
	
	// API: Users
	.client({
		pin : 'role:api,path:users',
		type: 'amqp',
		url : 'amqp://rabbitmq-master'
	});

module.exports = function() {

	return seneca;

};
```

2.) I have read your answer but I have to admit I am still a bit confused. Say for example that I have a microservice that is carrying out some time consuming task, and it's at the moment a very "popular" microservice because a lot of traffic is using exactly that part of my app right now. What I want to do is bring in another exact copy of the same service, and have it also listen and carry out the same task (in order to lighten the load of the primary copy). So basically a load balancing. Would I be able to do it?

**Comment by vigneshnrfs** [comment]
Hi @originalexe. With regards to point 2 you can spawn multiple microsevices and the load will be balanced. I have tested it with my development environment.

**Comment by nfantone** [comment]
@OriginalEXE Regarding your first point, it's looking more and more like a bug. The name of your queue ends up being `seneca.res.pg:path:users,role:api,pin:role:api,path:users,type:amqp,url:amqp://rabbitmq-master`, which is totally absurd. Could you please try the `develop` branch and see if that fixes it?

On number two, it's as @vigneshnrfs said. If you start _n_ microservices each one calling `.listen`, you'll create _n_ consumers on the same queue. Consumers are used in a round-robin fashion among those available.

**Comment by OriginalEXE** [comment]
Thank you.

I tested it with the develop branch and it works fine, no error :)

**Comment by nfantone** [comment]
@OriginalEXE Great! I'll cut a new release as soon as I can, so you can install it from `npm`.

**Comment by vigneshnrfs** [comment]
@nfantone Sorry for opening this thread again. Just wanted a opinion on this.

> @vigneshnrfs You can. But it won't be exactly like a fanout exchange. And there are certain gotchas you'd have to be aware of. If you have multiple microservices registered with the same pin carrying on different tasks, you'll end up with multiple queues bound to the same routing key on a topic exchange (on default settings, at least). A fanout exchange doesn't care about the routing key, whereas in this topology you'd have to publish your messages with a certain pattern to make it work (which is automatically handled by the plugin).

>On the other hand, if you do that you'd have many responses (many listeners) for one request (a client). And that is not supported by default in Seneca. It is doable, but you are going to have to do grunt work to succeed.

Can I use seneca.prior for a fanout kind of exchange. By default I will have seneca.prior for every. In this case, I am not worried about the response that I will get from those exchanges. Will this kind of workaround have any issues?

**Comment by nfantone** [comment]
@vigneshnrfs How do `seneca.prior` and exchanges play along here? You lost me here.

> I am not worried about the response that I will get from those exchanges.
Still, you'd have to call the callback on each listener. Or have the client implement some kind of "fire and forget" mechanism. Maybe [this decorator](https://github.com/senecajs/seneca-fire-and-forget) could help.
