### ISSUE TITLE
Login Credential

### ISSUE THREAD

**Issue by richardzyx** [disintegrator/seneca-amqp-transport#3]
Hi there,

Thanks for the great work! After I updated the RabbitMQ version on our server, it seems that a login credential is required for all connections. I couldn't find a place to add user and password into options, and I am wondering if you have the time to do this small fix? If not, I can still just use the url to send the login credential for creating the connection, but I am afraid that would not be as clear as having the username and password in the options.

Thanks for the great support!

Best,
Richard

**Comment by richardzyx** [comment]
Also, it seems that as I add more producers and consumers, they all share the same queue with name "seneca_any_act". I realize it is a problem with the topic and pin functions, but can you tell me a way to create unique queues based on the matching pattern of the current service?

**Comment by nfantone** [comment]
@richardzyx I know you have moved away from this and created [node-microservice](https://www.npmjs.com/package/node-microservice), but better later than never:

+ Username and password can be specified in the `amqp://` connection URI, as you mentioned. Next updates, will let you configure them in the options object.
+  Single queue issue has been adressed in latest `master`.

Thanks for your feedback.
