### ISSUE TITLE
pin vs. pins

### ISSUE THREAD

**Issue by nfantone** [disintegrator/seneca-amqp-transport#7]
@disintegrator @geek Is there any difference between defining multiple clients declaring a `pin` and just a single client with a `pins` array? Concretely, I am comparing the following scenarios:

### Multiple clients

```javascript
var seneca = require('seneca')()
  .use('seneca-amqp-transport')
  .client({
    type: 'amqp',
    pin: 'name:contact'
  })
  .client({
    type: 'amqp',
    pin: 'role:email'
  });
```

### Single client with an array of pins

```javascript
var seneca = require('seneca')()
  .use('seneca-amqp-transport')
  .client({
    type: 'amqp',
    pins: ['name:contact', 'role:email']
  });
```

I'm asking this, because, currently, the plugin doesn't show the same behavior in those scenarios. First one will create two clients, each one with its own res queue; while the second one, creates only one.

Same question goes for listeners, actually. What about those?

**Comment by mcdonnelldean** [comment]
So, @geek can correct me here. But my understanding is they're working as expected. The first is saying I specifically want two clients (use case, multiple port numbers) the second is say I want both of these messages to go to the one client (use case, granular definition of multiple pins to one client).

Bear in mind too order is important. so client one has preference to client two if both declare the same pins, client one will be called before client two.

**Comment by nfantone** [comment]
@mcdonnelldean Great. You are confirming my suspicions, then. Thanks.
