### ISSUE TITLE
Does it have TLS/SSL support?

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [disintegrator/seneca-amqp-transport#8]

**Comment by nfantone** [comment]
@andriy-zhelvachenko I does now :metal: 

See the [updated documentation](https://github.com/disintegrator/seneca-amqp-transport/blob/develop/README.md#socket-options) for usage.

Please, feel free to close the issue if you have no further questions or comments.

**Comment by andriy-zhelvachenko** [comment]
Tnx. 

I did check the docs but had not seen socketsOptions sections

**Comment by nfantone** [comment]
@andriy-zhelvachenko You are welcome. As it currently stands, it's a bit hard to find, since it's in `develop`. 

@disintegrator We need to consider publishing a new release.
